COLORS = ["azul", "verde", "vermelho", "amarelo"]

COUNTDOWN_SECONDS = 3
FIRST_INPUT_LIMIT_SECONDS = 5
MIN_INPUT_LIMIT_SECONDS = 2
ROUND_RESULT_DELAY_SECONDS = 1.5
SHOW_COLOR_SECONDS = 0.75
SHOW_GAP_SECONDS = 0.1
GAME_OVER_SECONDS = 3
